config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  recipe_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
    render 'new'
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def new
     @ingredient = Ingredient.new
  end
  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end
  def show
     @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
    render 'new'
  end
  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    recipe =  Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
    render 'new'
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipe_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title, :autofocus => 'autofocus' %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  <br>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
  <br>
  <% Recipe.all.each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<div class="right">
<br>
edit book!
<br>
<%= render :partial => 'form' %>
</div>

app/views/books/index.html.erb
<% @books.each do |book| %>
<section>
<ol>
  <li>
    <ul>
      <li><%= image_tag(book.image) %></li>
      <li><%= link_to(book.title, book) %></li>
      <li><%= book.cuisine %></li>
      <li><%= book.chef %></li>
    </ul>
  </li>
</ol>
</section>
<% end %>

app/views/books/new.html.erb
<div class="right">
<br>
new book!
<br>
<%= render :partial => 'form' %>
</div>

app/views/books/show.html.erb
<div class="right">
<section>
<%= image_tag(@book.image) %>
<b><%= link_to(@book.title, @book) %></b><br>
<%= @book.cuisine %><br>
<%= @book.chef %>
<br>
<%= link_to '(edit)', edit_book_path(@book) %>
<%= link_to '(delete)', @book, :method => :delete, :confirm => 'do you really want to delete this nice book?' %>
</section>
</div>

<div class="3col">
<% @book.recipes.each do |recipe| %>
<section class="artist">
  <%= image_tag(recipe.image) %>
  <%= link_to(recipe.name, recipe) %>
<br>

<section class="ingredient">
  <% recipe.ingredients.each do |ingredient| %>
<section class="individual_ing">
    <%= image_tag(ingredient.image) %>
    <br>
    <%= ingredient.name %>
</section>
  <% end %>

</section>
</section>
   <% end %>
</div>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name, :autofocus => 'autofocus' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.label :measurement %>
  <%= f.text_field :measurement %>
  <br>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <br>
    <% Ingredient.order(:name).each do |ingredient| %>
      <span><%= ingredient.name %></span>
      <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients) %>
    <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<div class="right">
<br>
edit ingredients!
<br>
<%= render :partial => 'form' %>
</div>

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
<section>
<ol>
  <li>
    <ul>
      <li><%= image_tag(ingredient.image) %></li>
      <li><%= link_to(ingredient.name, ingredient) %></li>
      <li><%= ingredient.measurement %></li>
      <li><%= ingredient.cost %></li>
    </ul>
  </li>
</ol>
</section>
<% end %>

app/views/ingredients/new.html.erb
<div class="right">
<br>
new ingredient!
<br>
<%= render :partial => 'form' %>
</div>

app/views/ingredients/show.html.erb
<div class='show'>
  <%= link_to @ingredient.name, @ingredient %>
  <%= @ingredient.measurement %>
  <%= @ingredient.cost %>
  <%= image_tag(@ingredient.image, :class =>'show') %>
</div>
<div class='links'>
<%= link_to 'Delete', @ingredient, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130214Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="left">
  <nav>
  <ul>
    <li>EA.TS</li><br>
    <li><%= link_to('books', books_path) %></li>
    <br>
    <li><%= link_to('recipes', recipes_path) %></li><br>
    <li><%= link_to('ingredients', ingredients_path) %></li><br>
     <li><%= link_to('add a book', new_book_path) %></li>
    <br>
    <li><%= link_to('add a recipe', new_recipe_path) %></li>
        <br>
    <li><%= link_to('add an ingredient', new_ingredient_path) %></li>
  </ul>
</nav>
</div>

<%= yield %>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :name, :autofocus => 'autofocus' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.label :course %>
  <%= f.text_field :course %>
  <br>
  <%= f.label :cooktime %>
  <%= f.text_field :cooktime %>
  <br>
  <%= f.label :servingsize %>
  <%= f.text_field :servingsize %>
  <br>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <br>
  <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<div class="right">
<br>
edit recipe!
<br>
<%= render :partial => 'form' %>
</div>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
<section>
<ol>
  <li>
    <ul>
      <li><%= image_tag(recipe.image) %></li>
      <li><%= link_to(recipe.name, recipe) %></li>
      <li><%= recipe.cooktime %></li>
      <li><%= recipe.course %></li>
      <li><%= recipe.servingsize %></li>
      <li><%= recipe.instructions %></li>
    </ul>
  </li>
</ol>
</section>
<% end %>

app/views/recipes/new.html.erb
<div class="right">
<br>
new recipe!
<br>
<%= render :partial => 'form' %>
</div>

app/views/recipes/show.html.erb
<div class='show'>
  <%= link_to @recipe.name, @recipe %>
  <%= @recipe.course %>
  <%= @recipe.cooktime %>
  <%= @recipe.servingsize %>
  <%= @recipe.instructions %>
  <%= image_tag(@recipe.image, :class =>'show') %>
</div>
<div class='links'>
<%= link_to 'Delete', @recipe, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %>
</div>